import { Food } from './app/shared/models/Food';
import { Tag } from './app/shared/models/Tag';

export const sample_foods: Food[] = [
  {
    id: '1',
    name: 'jollof rice',
    price: 9,
    cookTime: '30-40mins',
    favorite: true,
    origins: ['Nigeria', 'Ghana', 'Western Africa'],
    stars: 4.0,
    imageUrl: 'assets/food-1.jpeg',
    tags: ['Fastfood', 'Lunch'],
  },
  {
    id: '2',
    name: 'goat-soup(isi-ewu)',
    price: 9,
    cookTime: '30-60mins',
    favorite: true,
    origins: ['Nigeria'],
    stars: 4.0,
    imageUrl: 'assets/food-2.jpeg',
    tags: ['Fastfood', 'Slowfood', 'Lunch'],
  },
  {
    id: '3',
    name: 'pounded yam and soup',
    price: 9,
    cookTime: '40-90mins',
    favorite: false,
    origins: ['Nigeria'],
    stars: 4.0,
    imageUrl: 'assets/food-3.jpeg',
    tags: ['Traditional', 'Lunch', 'Swallow'],
  },
  {
    id: '4',
    name: 'akara(fried bean cake)',
    price: 9,
    cookTime: '15-20mins',
    favorite: true,
    origins: ['Nigeria', 'Ghana'],
    stars: 4.0,
    imageUrl: 'assets/food-4.jpeg',
    tags: ['Traditional', 'Fry', 'Breakfast'],
  },
  {
    id: '5',
    name: 'meat pepper-soup',
    price: 9,
    cookTime: '30-40mins',
    favorite: false,
    origins: ['Nigeria'],
    stars: 4.0,
    imageUrl: 'assets/food-5.jpeg',
    tags: ['Traditional', 'Lunch'],
  },
  {
    id: '6',
    name: 'vegetable pizza',
    price: 9,
    cookTime: '40-90mins',
    favorite: false,
    origins: ['Italy', 'Greece'],
    stars: 4.0,
    imageUrl: 'assets/food-6.jpeg',
    tags: ['Fastfood', 'Pizza', 'Lunch'],
  },
];
export const sample_tags: Tag[] = [
  { name: 'All', count: 6 },
  { name: 'Traditional', count: 6 },
  { name: 'Fastfood', count: 6 },
  { name: 'Slowfood', count: 6 },
  { name: 'Lunch', count: 6 },
  { name: 'Pizza', count: 6 },
  { name: 'Breakfast', count: 6 },
  { name: 'Fry', count: 6 },
  { name: 'Swallow', count: 6 },
];
